name: Fetch ALDI finds prices

on:
    schedule:
        - cron: '0 7 * * 0'  # Runs at midnight PST on Sundays
    workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2  

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas boto3 pyarrow vl-convert-python altair altair_saver altair-stiles lxml

    - name: Run scraper
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python fetch_process.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: aldi_finds
        path: data/processed/*.csv

    - name: Configure Git
      run: |
        git config --global user.name 'Matt Stiles'
        git config --global user.email 'haekeostiles@gmail.com'